"""Modify Comment.ip_address_prefix to ip_address and update length

Revision ID: 15af1d81810b
Revises: e37e534e4822
Create Date: 2025-05-24 22:43:13.540579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15af1d81810b'
down_revision = 'e37e534e4822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.drop_column('ip_address_prefix')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address_prefix', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
