"""Add Category model and relationship to Post

Revision ID: 31905617c2e2
Revises: def1273bdbe4
Create Date: 2025-05-25 17:43:46.300915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31905617c2e2'
down_revision = 'def1273bdbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if not inspector.has_table('category'):
        op.create_table('category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
        )

    with op.batch_alter_table('post', schema=None) as batch_op:
        post_columns = [c['name'] for c in inspector.get_columns('post')]
        if 'category_id' not in post_columns:
            batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=200),
               existing_nullable=False)
        if 'category_id' in post_columns:
            batch_op.create_foreign_key('fk_post_category_id_category', 'category', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_category_id_category', type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=140),
               existing_nullable=False)
        batch_op.drop_column('category_id')

    op.drop_table('category')
    # ### end Alembic commands ###
