"""Add alt_text to Post model

Revision ID: 33283563f5cc
Revises: 1574022584eb
Create Date: 2025-05-23 22:32:48.537240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33283563f5cc'
down_revision = '1574022584eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('alt_text')

    # ### end Alembic commands ###
