"""add is_published and published_at to post table

Revision ID: 3efba67b8f56
Revises: 116c55483add
Create Date: 2025-05-24 12:40:42.060574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3efba67b8f56'
down_revision = '116c55483add'
branch_labels = None
depends_on = None


def upgrade():
    # Attempt to drop the temporary table if it exists from a previous failed migration
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_post')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('video_embed_url',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('video_embed_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('image_filename',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('published_at')
        batch_op.drop_column('is_published')

    # ### end Alembic commands ###
