"""Initial migration

Revision ID: 452bdfc28a3e
Revises: 
Create Date: 2025-05-27 16:20:31.056363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452bdfc28a3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_title', sa.String(length=100), nullable=True),
    sa.Column('site_description', sa.Text(), nullable=True),
    sa.Column('site_domain', sa.String(length=255), nullable=True),
    sa.Column('favicon_filename', sa.String(length=255), nullable=True),
    sa.Column('posts_per_page', sa.Integer(), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=True),
    sa.Column('admin_github_url', sa.String(length=255), nullable=True),
    sa.Column('ad_sense_code', sa.Text(), nullable=True),
    sa.Column('google_analytics_id', sa.String(length=50), nullable=True),
    sa.Column('footer_copyright_text', sa.String(length=255), nullable=True),
    sa.Column('about_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_filename', sa.String(length=255), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('video_embed_url', sa.String(length=300), nullable=True),
    sa.Column('meta_description', sa.String(length=300), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_published_at'), ['published_at'], unique=False)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_at'), ['created_at'], unique=False)

    op.create_table('page_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_view_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_view_timestamp'))

    op.drop_table('page_view')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_created_at'))

    op.drop_table('comment')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_published_at'))
        batch_op.drop_index(batch_op.f('ix_post_created_at'))

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('site_setting')
    op.drop_table('category')
    # ### end Alembic commands ###
