"""Remove slug column from Post table

Revision ID: 8dc21fcf9697
Revises: e31041c962f5
Create Date: 2025-05-24 22:28:25.196616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc21fcf9697'
down_revision = 'e31041c962f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_slug'), ['slug'], unique=1)

    # ### end Alembic commands ###
