
"""Add AdSense configuration fields

Revision ID: add_adsense_fields
Revises: ed453da69303
Create Date: 2025-06-04 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_adsense_fields'
down_revision = 'ed453da69303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_adsense_publisher_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('google_adsense_auto_ads', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('adsense_header_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('adsense_sidebar_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('adsense_content_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('adsense_footer_code', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.drop_column('adsense_footer_code')
        batch_op.drop_column('adsense_content_code')
        batch_op.drop_column('adsense_sidebar_code')
        batch_op.drop_column('adsense_header_code')
        batch_op.drop_column('google_adsense_auto_ads')
        batch_op.drop_column('google_adsense_publisher_id')

    # ### end Alembic commands ###
