"""add about_content to site_settings

Revision ID: bd853afb69ec
Revises: 31905617c2e2
Create Date: 2025-05-26 00:41:26.759193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd853afb69ec'
down_revision = '31905617c2e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_post_category_id', 'category', ['category_id'], ['id'])

    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.drop_column('about_content')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_post_category_id', type_='foreignkey')

    # ### end Alembic commands ###
