"""Add SiteSetting model

Revision ID: d80489f170b4
Revises: da2b27d302d6
Create Date: 2025-05-25 01:55:56.976505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd80489f170b4'
down_revision = 'da2b27d302d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.alter_column('site_title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('favicon_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('admin_twitter_url')
        batch_op.drop_column('admin_linkedin_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_linkedin_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('admin_twitter_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('favicon_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('site_title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
