"""Change favicon_url to favicon_filename in SiteSetting

Revision ID: def1273bdbe4
Revises: d80489f170b4
Create Date: 2025-05-25 02:16:16.771753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def1273bdbe4'
down_revision = 'd80489f170b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_filename', sa.String(length=255), nullable=True))
        batch_op.drop_column('favicon_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favicon_url', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('favicon_filename')

    # ### end Alembic commands ###
