"""Add ip_address_prefix to Comment model

Revision ID: e37e534e4822
Revises: 8dc21fcf9697
Create Date: 2025-05-24 22:40:44.142534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37e534e4822'
down_revision = '8dc21fcf9697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address_prefix', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_column('ip_address_prefix')

    # ### end Alembic commands ###
