"""Add Media model

Revision ID: ed453da69303
Revises: 45319564c422
Create Date: 2025-06-02 01:40:57.329355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed453da69303'
down_revision = '45319564c422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('meta_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_description', sa.VARCHAR(length=300), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
